name: Publish package to the Maven Central Repository

on:
  workflow_dispatch:
  push:
    branches:
      - features/git-action-release
#    tags:
#      - v*

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
        with:
          ref: features/git-action-release
      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: central
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
      - name: Publish package
        run: mvn --batch-mode clean deploy -P release
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}
